In [32]:
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

In [25]:
df_all_profiles = pd.read_csv("C:\\Priyanka\\Datasets\\Dating profiles.csv")

In [30]:
df_female=df_all_profiles[df_all_profiles['Gender']=='F']

In [29]:
df_male=df_all_profiles[df_all_profiles['Gender']=='M']

In [75]:
f1 = df_female.iloc[0,2:].values


In [76]:
f2 = df_female.iloc[1,2:].values


In [77]:
M1 = df_male.iloc[0,2:].values
M2 = df_male.iloc[1,2:].values


In [67]:
cosine_similarity(f1,M1)

array([[0.88888889]])

In [78]:
f1 = f1.reshape(1,-1)
M1 = M1.reshape(1,-1)

In [79]:
f2 = f2.reshape(1,-1)
M2 = M2.reshape(1,-1)

In [80]:
cosine_similarity(f1,M2)

array([[0.55555556]])

In [82]:
cosine_similarity(f2,M2)

array([[0.47140452]])